"""
Course Number: ENGR 13300
Semester: Fall 2025

Description:
    Calculating turbine power and energy output over time given initial conditions

Assignment Information:
    Assignment:     8.2.3 Py2 Team 3 Main
    Team ID:        Fall - 06
    Author:         Milan Shah, shah1237@purdue.edu
    Date:           09/19/2025

Contributors:
    Name, login@purdue [repeat for each]

    My contributor(s) helped me:
    [ ] understand the assignment expectations without
        telling me how they will approach it.
    [ ] understand different ways to think about a solution
        without helping me plan my solution.
    [ ] think through the meaning of a specific error or
        bug present in my code without looking at my code.
    Note that if you helped somebody else with their code, you
    have to list that person as a contributor here as well.

Academic Integrity Statement:
    I have not used source code obtained from any unauthorized
    source, either modified or unmodified; nor have I provided
    another student access to my code.  The project I am
    submitting is my own original work.
"""


from py2_team_3_turbine_power_6 import turbine_power
from py2_team_3_heater_6 import heater


def main():
    #variables input
    length, rho, cP = 50, 1.23, 0.4
    velocity = float(input("Enter the velocity in m/s: "))
    timeh = float(input("Enter the time in hours: "))

    #setting power and energy with functions
    power = turbine_power(rho, length, velocity, cP)
    energy = heater(power, timeh * 3600)

    print(f"The power generated by the turbine is {float(round(power, 1))} W")
    print(f"The amount of heat output by the heater is {round(energy, 1)} J")

if __name__ == "__main__":
    main()
